services:
  db:
    container_name: express-rest-db
    restart: always
    image: postgres
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
  api:
    container_name: express-rest
    restart: always
    image: express-rest
    build:
      context: .
    env_file:
      - ./.env
    # Essential for nodemon restart working
    volumes:
      - ./:/usr/src/app
    networks:
      - network
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/inventory

networks:
  network:

volumes:
  db:
