name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy express-rest \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --min-instances 1 \
            --max-instances 5 \
            --concurrency 80 \
            --memory 512Mi \
            --allow-unauthenticated
