name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest ./express-rest

      - name: Push to Google Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy express-rest \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/express-rest \
            --platform managed \
            --region asia-southeast2 \
            --allow-unauthenticated \
            --port 8080
